spring:
  port: 80
  config:
    import: optional:file:.env[.properties]
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${TZ}&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:sql/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT}
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}